const MOCK_EXPANSIONS = [
  {
    id: 2170,
    code: "wtr",
    name: "Welcome to Rathe",
  },
  {
    id: 2171,
    code: "arc",
    name: "Arcane Rising",
  },
  {
    id: 2172,
    code: "cru",
    name: "Crucible of War",
  },
  { id: 2173, code: "mon", name: "Monarch - Unlimited" },
  { id: 2194, code: "lgs", name: "Armory Events" },
  {
    id: 2202,
    code: "fabpro",
    name: "Flesh and Blood Promos",
  },
  {
    id: 2409,
    code: "ele",
    name: "Tales of Aria - Unlimited",
  },
  { id: 2599, code: "op", name: "Organized Play" },
  { id: 2601, code: "jdg", name: "Judge Promos" },
  { id: 2902, code: "evr1", name: "Everfest - First" },
  { id: 3030, code: "1hp", name: "History Pack 1" },
  { id: 3031, code: "upr", name: "Uprising" },
  {
    id: 3068,
    code: "cru1",
    name: "Crucible of War - First",
  },
  { id: 3073, code: "arc1", name: "Arcane Rising - First" },
  { id: 3074, code: "mon1", name: "Monarch - First" },
  { id: 3075, code: "ele1", name: "Tales of Aria - First" },
  { id: 3130, code: "dyn", name: "Dynasty" },
  { id: 3223, code: "out", name: "Outsiders" },
  { id: 3267, code: "her", name: "Hero Card Promos" },
  { id: 3362, code: "dtd", name: "Dusk till dawn" },
  { id: 3465, code: "evo", name: "Bright Lights" },
  { id: 3559, code: "heh", name: "Heavy Hitters" },
  { id: 3783, code: "ros", name: "Rosetta" },
  { id: 3911, code: "rap", name: "Rosetta - Archive Pack" },
  {
    id: 3912,
    code: "map",
    name: "Part the Mistveil - Archive Pack",
  },
  { id: 3938, code: "hnt", name: "The Hunted" },
  {
    id: 3973,
    code: "gap",
    name: "Archive Mastery Pack - Guardian",
  },
  { id: 4055, code: "gem", name: "GEM Pack" },
  { id: 4116, code: "sea", name: "High Seas" },
  { id: 4153, code: "mpg", name: "Mastery Pack: Guardian" },
  {
    id: 4156,
    code: "sea-t",
    name: "High Seas - Treasure Pack",
  },
  { id: 4251, code: "sup", name: "Super Slam" },
];

module.exports = { MOCK_EXPANSIONS };